<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'asset_number' => '0012',
                'serial_number' => '',
                'qr_code' => null,
                'name' => 'Meja Lipat',
                'room_id' => 3,
                'quantity' => 1,
                'source' => 'Oracle',
                'acquisition_year' => 2009,
                'placed_in_service_at' => '2025-12-06',
                'fiscal_group' => '2',
                'status' => 'maintenance',
                'condition' => 'good',
                'created_at' => '2025-12-06 02:29:26',
                'updated_at' => '2025-12-07 10:21:33',
            ],
            [
                'asset_number' => '0001',
                'serial_number' => '',
                'qr_code' => null,
                'name' => 'Jangka Sorong 1',
                'room_id' => 3,
                'quantity' => 1,
                'source' => 'Stei',
                'acquisition_year' => 2025,
                'placed_in_service_at' => '2025-12-07',
                'fiscal_group' => '3',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-07 09:37:32',
                'updated_at' => '2025-12-07 20:47:14',
            ],
            [
                'asset_number' => '0002',
                'serial_number' => '',
                'qr_code' => null,
                'name' => 'Jangka Sorong 2',
                'room_id' => 1,
                'quantity' => 1,
                'source' => 'Stei',
                'acquisition_year' => 2025,
                'placed_in_service_at' => '2025-12-07',
                'fiscal_group' => '3',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-07 09:38:06',
                'updated_at' => '2025-12-07 09:38:06',
            ],
            [
                'asset_number' => '0013',
                'serial_number' => '',
                'qr_code' => null,
                'name' => 'Meja Lipat',
                'room_id' => 3,
                'quantity' => 1,
                'source' => 'Oracle',
                'acquisition_year' => 2009,
                'placed_in_service_at' => '2025-12-06',
                'fiscal_group' => '2',
                'status' => 'maintenance',
                'condition' => 'good',
                'created_at' => '2025-12-06 02:29:26',
                'updated_at' => '2025-12-07 10:21:33',
            ],
            [
                'asset_number' => '1',
                'serial_number' => 'SN-62781',
                'qr_code' => null,
                'name' => 'Meja',
                'room_id' => 1,
                'quantity' => 1,
                'source' => '-',
                'acquisition_year' => 2019,
                'placed_in_service_at' => '2025-12-17',
                'fiscal_group' => '1',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-17 07:33:46',
                'updated_at' => '2025-12-17 07:33:46',
            ],
            [
                'asset_number' => '0015',
                'serial_number' => '',
                'qr_code' => null,
                'name' => 'Jangka Sorong 1',
                'room_id' => 3,
                'quantity' => 1,
                'source' => 'Stei',
                'acquisition_year' => 2025,
                'placed_in_service_at' => '2025-12-07',
                'fiscal_group' => '3',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-07 09:37:32',
                'updated_at' => '2025-12-07 20:47:14',
            ],
            [
                'asset_number' => '0016',
                'serial_number' => '',
                'qr_code' => null,
                'name' => 'Jangka Sorong 2',
                'room_id' => 1,
                'quantity' => 1,
                'source' => 'Stei',
                'acquisition_year' => 2025,
                'placed_in_service_at' => '2025-12-07',
                'fiscal_group' => '3',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-07 09:38:06',
                'updated_at' => '2025-12-07 09:38:06',
            ],
            [
                'asset_number' => '0020',
                'serial_number' => 'SN-62781',
                'qr_code' => null,
                'name' => 'Meja',
                'room_id' => 1,
                'quantity' => 1,
                'source' => '-',
                'acquisition_year' => 2019,
                'placed_in_service_at' => '2025-12-17',
                'fiscal_group' => '1',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-17 07:33:46',
                'updated_at' => '2025-12-17 07:33:46',
            ],
            [
                'asset_number' => '45',
                'serial_number' => 'SN-62324',
                'qr_code' => 'null',
                'name' => 'Meja 23',
                'room_id' => 1,
                'quantity' => 1,
                'source' => '-',
                'acquisition_year' => 2019,
                'placed_in_service_at' => '2025-12-18',
                'fiscal_group' => '1',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-18 02:57:52',
                'updated_at' => '2025-12-18 02:57:56',
            ],
            [
                'asset_number' => '0323',
                'serial_number' => 'SN-624112',
                'qr_code' => 'null',
                'name' => 'Meja',
                'room_id' => 1,
                'quantity' => 1,
                'source' => '2018',
                'acquisition_year' => 2024,
                'placed_in_service_at' => null,
                'fiscal_group' => '4',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-18 03:13:03',
                'updated_at' => '2025-12-18 03:13:03',
            ],
            [
                'asset_number' => '5326',
                'serial_number' => 'eq',
                'qr_code' => 'null',
                'name' => 'Meja',
                'room_id' => 1,
                'quantity' => 1,
                'source' => 'ewq',
                'acquisition_year' => 2014,
                'placed_in_service_at' => '2025-12-19',
                'fiscal_group' => null,
                'status' => 'borrowed',
                'condition' => 'good',
                'created_at' => '2025-12-18 03:19:26',
                'updated_at' => '2025-12-18 04:03:21',
            ],
            [
                'asset_number' => '7323',
                'serial_number' => 'SN-31241',
                'qr_code' => 'null',
                'name' => 'Tes QR',
                'room_id' => 1,
                'quantity' => 10,
                'source' => '2018',
                'acquisition_year' => 2020,
                'placed_in_service_at' => '2025-12-18',
                'fiscal_group' => '4',
                'status' => 'borrowed',
                'condition' => 'good',
                'created_at' => '2025-12-18 04:05:12',
                'updated_at' => '2025-12-18 04:10:47',
            ],
            [
                'asset_number' => '7328',
                'serial_number' => 'SN-62324',
                'qr_code' => 'null',
                'name' => 'Meja 23',
                'room_id' => 1,
                'quantity' => 1,
                'source' => '-',
                'acquisition_year' => 2019,
                'placed_in_service_at' => '2025-12-18',
                'fiscal_group' => '1',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-18 02:57:52',
                'updated_at' => '2025-12-18 02:57:56',
            ],
            [
                'asset_number' => '3213',
                'serial_number' => 'SN-624112',
                'qr_code' => 'null',
                'name' => 'Meja',
                'room_id' => 1,
                'quantity' => 1,
                'source' => '2018',
                'acquisition_year' => 2024,
                'placed_in_service_at' => null,
                'fiscal_group' => '4',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-18 03:13:03',
                'updated_at' => '2025-12-18 03:13:03',
            ],
            [
                'asset_number' => '7256',
                'serial_number' => 'eq',
                'qr_code' => 'null',
                'name' => 'Meja',
                'room_id' => 1,
                'quantity' => 1,
                'source' => 'ewq',
                'acquisition_year' => 2014,
                'placed_in_service_at' => '2025-12-19',
                'fiscal_group' => null,
                'status' => 'borrowed',
                'condition' => 'good',
                'created_at' => '2025-12-18 03:19:26',
                'updated_at' => '2025-12-18 04:03:21',
            ],
            [
                'asset_number' => '9283',
                'serial_number' => 'SN-31241',
                'qr_code' => 'null',
                'name' => 'Tes QR',
                'room_id' => 1,
                'quantity' => 10,
                'source' => '2018',
                'acquisition_year' => 2020,
                'placed_in_service_at' => '2025-12-18',
                'fiscal_group' => '4',
                'status' => 'borrowed',
                'condition' => 'good',
                'created_at' => '2025-12-18 04:05:12',
                'updated_at' => '2025-12-18 04:10:47',
            ],
        ];

        foreach ($items as $data) {
            $item = Item::create($data);
            $this->generateQrForSeeder($item);
        }
    }
        private function generateQrForSeeder(Item $item): void
        {
            $qrPath = 'qr/items/' . $item->id . '.svg';
            $item->load('room');
            
            $payload = "Item Name: " . $item->name . "\r\n" .
                    "Asset No: " . ($item->asset_number ?? 'N/A') . "\r\n" .
                    "Serial No: " . $item->serial_number . "\r\n" .
                    "Room Name: " . ($item->room->name ?? 'N/A') . "\r\n" .
                    "Condition: " . $item->condition;

            $qrContent = QrCode::format('svg')
                ->size(300)
                ->margin(2)
                ->errorCorrection('H')
                ->generate($payload);

            Storage::disk('public')->put($qrPath, $qrContent);
            $item->update(['qr_code' => $qrPath]);
    }
}