<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        Item::insert([
            [
                'asset_number' => '0012',
                'serial_number' => '',
                'qr_code' => null,
                'name' => 'Meja Lipat',
                'room_id' => 3,
                'quantity' => 1,
                'source' => 'Oracle',
                'acquisition_year' => 2009,
                'placed_in_service_at' => '2025-12-06',
                'fiscal_group' => '2',
                'status' => 'maintenance',
                'condition' => 'good',
                'created_at' => '2025-12-06 02:29:26',
                'updated_at' => '2025-12-07 10:21:33',
            ],
            [
                'asset_number' => '0001',
                'serial_number' => '',
                'qr_code' => null,
                'name' => 'Jangka Sorong 1',
                'room_id' => 3,
                'quantity' => 1,
                'source' => 'Stei',
                'acquisition_year' => 2025,
                'placed_in_service_at' => '2025-12-07',
                'fiscal_group' => '3',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-07 09:37:32',
                'updated_at' => '2025-12-07 20:47:14',
            ],
            [
                'asset_number' => '0002',
                'serial_number' => '',
                'qr_code' => null,
                'name' => 'Jangka Sorong 2',
                'room_id' => 1,
                'quantity' => 1,
                'source' => 'Stei',
                'acquisition_year' => 2025,
                'placed_in_service_at' => '2025-12-07',
                'fiscal_group' => '3',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-07 09:38:06',
                'updated_at' => '2025-12-07 09:38:06',
            ],
            [
                'asset_number' => '0012',
                'serial_number' => '',
                'qr_code' => null,
                'name' => 'Meja Lipat',
                'room_id' => 3,
                'quantity' => 1,
                'source' => 'Oracle',
                'acquisition_year' => 2009,
                'placed_in_service_at' => '2025-12-06',
                'fiscal_group' => '2',
                'status' => 'maintenance',
                'condition' => 'good',
                'created_at' => '2025-12-06 02:29:26',
                'updated_at' => '2025-12-07 10:21:33',
            ],
            [
                'asset_number' => '1',
                'serial_number' => 'SN-62781',
                'qr_code' => null,
                'name' => 'Meja',
                'room_id' => 1,
                'quantity' => 1,
                'source' => '-',
                'acquisition_year' => 2019,
                'placed_in_service_at' => '2025-12-17',
                'fiscal_group' => '1',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-17 07:33:46',
                'updated_at' => '2025-12-17 07:33:46',
            ],
            [
                'asset_number' => '0001',
                'serial_number' => '',
                'qr_code' => null,
                'name' => 'Jangka Sorong 1',
                'room_id' => 3,
                'quantity' => 1,
                'source' => 'Stei',
                'acquisition_year' => 2025,
                'placed_in_service_at' => '2025-12-07',
                'fiscal_group' => '3',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-07 09:37:32',
                'updated_at' => '2025-12-07 20:47:14',
            ],
            [
                'asset_number' => '0002',
                'serial_number' => '',
                'qr_code' => null,
                'name' => 'Jangka Sorong 2',
                'room_id' => 1,
                'quantity' => 1,
                'source' => 'Stei',
                'acquisition_year' => 2025,
                'placed_in_service_at' => '2025-12-07',
                'fiscal_group' => '3',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-07 09:38:06',
                'updated_at' => '2025-12-07 09:38:06',
            ],
            [
                'asset_number' => '1',
                'serial_number' => 'SN-62781',
                'qr_code' => null,
                'name' => 'Meja',
                'room_id' => 1,
                'quantity' => 1,
                'source' => '-',
                'acquisition_year' => 2019,
                'placed_in_service_at' => '2025-12-17',
                'fiscal_group' => '1',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-17 07:33:46',
                'updated_at' => '2025-12-17 07:33:46',
            ],
            [
                'asset_number' => '45',
                'serial_number' => 'SN-62324',
                'qr_code' => 'qr/items/9.svg',
                'name' => 'Meja 23',
                'room_id' => 1,
                'quantity' => 1,
                'source' => '-',
                'acquisition_year' => 2019,
                'placed_in_service_at' => '2025-12-18',
                'fiscal_group' => '1',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-18 02:57:52',
                'updated_at' => '2025-12-18 02:57:56',
            ],
            [
                'asset_number' => '3213',
                'serial_number' => 'SN-624112',
                'qr_code' => 'qr/items/10.svg',
                'name' => 'Meja',
                'room_id' => 1,
                'quantity' => 1,
                'source' => '2018',
                'acquisition_year' => 2024,
                'placed_in_service_at' => null,
                'fiscal_group' => '4',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-18 03:13:03',
                'updated_at' => '2025-12-18 03:13:03',
            ],
            [
                'asset_number' => 'deqeq',
                'serial_number' => 'eq',
                'qr_code' => 'qr/items/11.svg',
                'name' => 'Meja',
                'room_id' => 1,
                'quantity' => 1,
                'source' => 'ewq',
                'acquisition_year' => 2014,
                'placed_in_service_at' => '2025-12-19',
                'fiscal_group' => null,
                'status' => 'borrowed',
                'condition' => 'good',
                'created_at' => '2025-12-18 03:19:26',
                'updated_at' => '2025-12-18 04:03:21',
            ],
            [
                'asset_number' => 'QR',
                'serial_number' => 'SN-31241',
                'qr_code' => 'qr/items/12.svg',
                'name' => 'Tes QR',
                'room_id' => 1,
                'quantity' => 10,
                'source' => '2018',
                'acquisition_year' => 2020,
                'placed_in_service_at' => '2025-12-18',
                'fiscal_group' => '4',
                'status' => 'borrowed',
                'condition' => 'good',
                'created_at' => '2025-12-18 04:05:12',
                'updated_at' => '2025-12-18 04:10:47',
            ],
            [
                'asset_number' => '45',
                'serial_number' => 'SN-62324',
                'qr_code' => 'qr/items/9.svg',
                'name' => 'Meja 23',
                'room_id' => 1,
                'quantity' => 1,
                'source' => '-',
                'acquisition_year' => 2019,
                'placed_in_service_at' => '2025-12-18',
                'fiscal_group' => '1',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-18 02:57:52',
                'updated_at' => '2025-12-18 02:57:56',
            ],
            [
                'asset_number' => '3213',
                'serial_number' => 'SN-624112',
                'qr_code' => 'qr/items/10.svg',
                'name' => 'Meja',
                'room_id' => 1,
                'quantity' => 1,
                'source' => '2018',
                'acquisition_year' => 2024,
                'placed_in_service_at' => null,
                'fiscal_group' => '4',
                'status' => 'available',
                'condition' => 'good',
                'created_at' => '2025-12-18 03:13:03',
                'updated_at' => '2025-12-18 03:13:03',
            ],
            [
                'asset_number' => 'deqeq',
                'serial_number' => 'eq',
                'qr_code' => 'qr/items/11.svg',
                'name' => 'Meja',
                'room_id' => 1,
                'quantity' => 1,
                'source' => 'ewq',
                'acquisition_year' => 2014,
                'placed_in_service_at' => '2025-12-19',
                'fiscal_group' => null,
                'status' => 'borrowed',
                'condition' => 'good',
                'created_at' => '2025-12-18 03:19:26',
                'updated_at' => '2025-12-18 04:03:21',
            ],
            [
                'asset_number' => 'QR',
                'serial_number' => 'SN-31241',
                'qr_code' => 'qr/items/12.svg',
                'name' => 'Tes QR',
                'room_id' => 1,
                'quantity' => 10,
                'source' => '2018',
                'acquisition_year' => 2020,
                'placed_in_service_at' => '2025-12-18',
                'fiscal_group' => '4',
                'status' => 'borrowed',
                'condition' => 'good',
                'created_at' => '2025-12-18 04:05:12',
                'updated_at' => '2025-12-18 04:10:47',
            ],
        ]);
    }
}