<?php

namespace Database\Seeders;

use App\Models\Print3D as PrintModel;
use Illuminate\Database\Seeder;

class PrintSeeder extends Seeder
{
    public function run(): void
    {
        PrintModel::insert([
            [
                'user_id' => 1,
                'printer_id' => null,
                'date' => '2025-12-09',
                'start_time' => '10:43:00',
                'end_time' => '11:43:00',
                'status' => 'pending',
                'file_name' => '1765251835_history_borrowings.pdf',
                'notes' => '10',
                'file_path' => 'prints/1765251835_history_borrowings.pdf',
                'material_type_id' => 1,
                'material_amount' => 2,
                'material_deducted' => 0,
                'material_unit' => 'gram',
                'material_source' => 'lab',
                'created_at' => '2025-12-09 03:43:56',
                'updated_at' => '2025-12-09 03:43:56',
            ],
            [
                'user_id' => 3,
                'printer_id' => null,
                'date' => '2025-12-12',
                'start_time' => '09:43:00',
                'end_time' => '11:43:00',
                'status' => 'pending',
                'file_name' => null,
                'notes' => '2',
                'file_path' => null,
                'material_type_id' => 1,
                'material_amount' => 2,
                'material_deducted' => 0,
                'material_unit' => 'gram',
                'material_source' => 'penelitian',
                'created_at' => '2025-12-10 02:43:12',
                'updated_at' => '2025-12-10 02:43:12',
            ],
            [
                'user_id' => 1,
                'printer_id' => 2,
                'date' => '2025-12-12',
                'start_time' => '15:43:00',
                'end_time' => '18:43:00',
                'status' => 'pending',
                'file_name' => null,
                'notes' => null,
                'file_path' => null,
                'material_type_id' => null,
                'material_amount' => null,
                'material_deducted' => 0,
                'material_unit' => null,
                'material_source' => null,
                'created_at' => '2025-12-10 02:43:42',
                'updated_at' => '2025-12-10 02:43:42',
            ],
            [
                'user_id' => 1,
                'printer_id' => 5,
                'date' => '2025-12-19',
                'start_time' => '14:28:00',
                'end_time' => '15:29:00',
                'status' => 'pending',
                'file_name' => null,
                'notes' => null,
                'file_path' => null,
                'material_type_id' => 4,
                'material_amount' => 10,
                'material_deducted' => 0,
                'material_unit' => 'gram',
                'material_source' => 'lab',
                'created_at' => '2025-12-17 07:29:25',
                'updated_at' => '2025-12-17 07:29:25',
            ],
            [
                'user_id' => 3,
                'printer_id' => 2,
                'date' => '2025-12-19',
                'start_time' => '15:22:00',
                'end_time' => '16:22:00',
                'status' => 'pending',
                'file_name' => null,
                'notes' => null,
                'file_path' => null,
                'material_type_id' => 2,
                'material_amount' => 1,
                'material_deducted' => 0,
                'material_unit' => 'gram',
                'material_source' => 'penelitian',
                'created_at' => '2025-12-17 08:22:53',
                'updated_at' => '2025-12-17 08:22:53',
            ],
            [
                'user_id' => 1,
                'printer_id' => null,
                'date' => '2025-12-19',
                'start_time' => '19:00:00',
                'end_time' => '23:13:00',
                'status' => 'pending',
                'file_name' => null,
                'notes' => null,
                'file_path' => null,
                'material_type_id' => 1,
                'material_amount' => 10,
                'material_deducted' => 0,
                'material_unit' => 'gram',
                'material_source' => 'penelitian',
                'created_at' => '2025-12-17 08:24:34',
                'updated_at' => '2025-12-17 08:24:34',
            ],
        ]);
    }
}